In [4]:
#read csv

In [5]:
import pandas as pd

In [6]:
csv_movies = pd.read_csv(r"C:\Users\ATEEQUE\Downloads\data set of madam .csv")

In [7]:
csv_movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [8]:
csv_movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [9]:
csv_movies.shape

(1000, 10)

In [10]:
csv_movies.columns

Index(['Series_Title', 'Released_Year', 'Runtime', 'Genre', 'IMDB_Rating',
       'Director', 'Star1', 'No_of_Votes', 'Gross', 'Metascore'],
      dtype='str')

In [11]:
csv_movies.dtypes

Series_Title         str
Released_Year        str
Runtime            int64
Genre                str
IMDB_Rating      float64
Director             str
Star1                str
No_of_Votes        int64
Gross            float64
Metascore        float64
dtype: object

In [12]:
csv_movies["Series_Title"]

0      The Shawshank Redemption
1                 The Godfather
2               The Dark Knight
3        The Godfather: Part II
4                  12 Angry Men
                 ...
995      Breakfast at Tiffany's
996                       Giant
997       From Here to Eternity
998                    Lifeboat
999                The 39 Steps
Name: Series_Title, Length: 1000, dtype: str

In [13]:
csv_movies[["Series_Title","IMDB_Rating"]]

                 Series_Title  IMDB_Rating
0    The Shawshank Redemption          9.3
1               The Godfather          9.2
2             The Dark Knight          9.0
3      The Godfather: Part II          9.0
4                12 Angry Men          9.0
..                        ...          ...
995    Breakfast at Tiffany's          7.6
996                     Giant          7.6
997     From Here to Eternity          7.6
998                  Lifeboat          7.6
999              The 39 Steps          7.6

[1000 rows x 2 columns]

In [14]:
csv_movies[["Series_Title","Director","IMDB_Rating","No_of_Votes"]]

                 Series_Title              Director  IMDB_Rating  No_of_Votes
0    The Shawshank Redemption        Frank Darabont          9.3      2343110
1               The Godfather  Francis Ford Coppola          9.2      1620367
2             The Dark Knight     Christopher Nolan          9.0      2303232
3      The Godfather: Part II  Francis Ford Coppola          9.0      1129952
4                12 Angry Men          Sidney Lumet          9.0       689845
..                        ...                   ...          ...          ...
995    Breakfast at Tiffany's         Blake Edwards          7.6       166544
996                     Giant        George Stevens          7.6        34075
997     From Here to Eternity        Fred Zinnemann          7.6        43374
998                  Lifeboat      Alfred Hitchcock          7.6        26471
999              The 39 Steps      Alfred Hitchcock          7.6        51853

[1000 rows x 4 columns]

In [15]:
csv_movies[csv_movies['IMDB_Rating']>8.5]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
6,Pulp Fiction,1994,154,Crime,8.9,Quentin Tarantino,John Travolta,1826188,107928762.0,94.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0
9,Fight Club,1999,139,Drama,8.8,David Fincher,Brad Pitt,1854740,37030102.0,66.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
11,Forrest Gump,1994,142,Drama,8.8,Robert Zemeckis,Tom Hanks,1809221,330252182.0,82.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
14,The Matrix,1999,136,Action,8.7,Lana Wachowski,Lilly Wachowski,1676426,171479930.0,73.0
15,Goodfellas,1990,146,Biography,8.7,Martin Scorsese,Robert De Niro,1020727,46836394.0,90.0
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
17,One Flew Over the Cuckoo's Nest,1975,133,Drama,8.7,Milos Forman,Jack Nicholson,918088,112000000.0,83.0
18,Hamilton,2020,160,Biography,8.6,Thomas Kail,Lin-Manuel Miranda,55291,440984783.0,90.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
20,Soorarai Pottru,2020,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648.0,NaN
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
22,Cidade de Deus,2002,130,Crime,8.6,Fernando Meirelles,Kátia Lund,699256,7563397.0,79.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
24,Saving Private Ryan,1998,169,Drama,8.6,Steven Spielberg,Tom Hanks,1235804,216540909.0,91.0
25,The Green Mile,1999,189,Crime,8.6,Frank Darabont,Tom Hanks,1147794,136801374.0,61.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
28,The Silence of the Lambs,1991,118,Crime,8.6,Jonathan Demme,Jodie Foster,1270197,130742922.0,85.0
29,Star Wars,1977,121,Action,8.6,George Lucas,Mark Hamill,1231473,322740140.0,90.0
30,Seppuku,1962,133,Action,8.6,Masaki Kobayashi,Tatsuya Nakadai,42004,373978394.0,85.0
31,Shichinin no samurai,1954,207,Action,8.6,Akira Kurosawa,Toshirô Mifune,315744,269061.0,98.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0

In [16]:
csv_movies[csv_movies['Released_Year'] > "2000"]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
...,...,...,...,...,...,...,...,...,...,...
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
949,Blow,2001,124,Biography,7.6,Ted Demme,Johnny Depp,240714,52990775.0,52.0
950,Enemy at the Gates,2001,131,Drama,7.6,Jean-Jacques Annaud,Jude Law,243729,51401758.0,53.0
951,Minority Report,2002,145,Action,7.6,Steven Spielberg,Tom Cruise,508417,132072926.0,80.0
966,Apollo 13,PG,140,Adventure,7.6,Ron Howard,Tom Hanks,269197,173837933.0,77.0

In [17]:
csv_movies[csv_movies['Runtime'] > 180]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
25,The Green Mile,1999,189,Crime,8.6,Frank Darabont,Tom Hanks,1147794,136801374.0,61.0
31,Shichinin no samurai,1954,207,Action,8.6,Akira Kurosawa,Toshirô Mifune,315744,269061.0,98.0
59,Avengers: Endgame,2019,181,Action,8.4,Anthony Russo,Joe Russo,809955,858373000.0,78.0
71,Once Upon a Time in America,1984,229,Crime,8.4,Sergio Leone,Robert De Niro,311365,5321508.0,NaN
116,Lawrence of Arabia,1962,228,Adventure,8.3,David Lean,Peter O'Toole,268085,44824144.0,100.0
139,Bhaag Milkha Bhaag,2013,186,Biography,8.2,Rakeysh Omprakash Mehra,Farhan Akhtar,61137,1626289.0,NaN
140,Gangs of Wasseypur,2012,321,Action,8.2,Anurag Kashyap,Manoj Bajpayee,82365,5257741.0,89.0
156,"Swades: We, the People",2004,210,Drama,8.2,Ashutosh Gowariker,Shah Rukh Khan,83005,1223240.0,NaN
177,Sholay,1975,204,Action,8.2,Ramesh Sippy,Sanjeev Kumar,51284,932069480.0,NaN
206,Kis Uykusu,2014,196,Drama,8.1,Nuri Bilge Ceylan,Haluk Bilginer,46547,165520.0,88.0
240,Dil Chahta Hai,2001,183,Comedy,8.1,Farhan Akhtar,Aamir Khan,66803,300000.0,NaN
247,Lagaan: Once Upon a Time in India,2001,224,Adventure,8.1,Ashutosh Gowariker,Aamir Khan,105036,70147.0,84.0
258,Dilwale Dulhania Le Jayenge,1995,189,Drama,8.1,Aditya Chopra,Shah Rukh Khan,63516,15121644.0,NaN
274,Fanny och Alexander,1982,188,Drama,8.1,Ingmar Bergman,Bertil Guve,57784,4971340.0,100.0
278,The Deer Hunter,1978,183,Drama,8.1,Michael Cimino,Robert De Niro,311361,48979328.0,86.0
281,Barry Lyndon,1975,185,Adventure,8.1,Stanley Kubrick,Ryan O'Neal,149843,36008144.0,89.0
290,Andrei Rublev,1966,205,Biography,8.1,Andrei Tarkovsky,Anatoliy Solonitsyn,46947,102021.0,NaN
300,Ben-Hur,1959,212,Adventure,8.1,William Wyler,Charlton Heston,219466,74700000.0,90.0
314,Gone with the Wind,1939,238,Drama,8.1,Victor Fleming,George Cukor,290074,198676459.0,97.0
374,Kal Ho Naa Ho,2003,186,Comedy,8.0,Nikkhil Advani,Preity Zinta,63460,1787378.0,54.0
383,Magnolia,1999,188,Drama,8.0,Paul Thomas Anderson,Tom Cruise,289742,22455976.0,77.0
400,JFK,1991,189,Drama,8.0,Oliver Stone,Kevin Costner,142110,70405498.0,72.0
402,Dances with Wolves,1990,181,Adventure,8.0,Kevin Costner,Kevin Costner,240266,184208848.0,72.0
411,Gandhi,1982,191,Biography,8.0,Richard Attenborough,Ben Kingsley,217664,52767889.0,79.0
422,Fiddler on the Roof,1971,181,Drama,8.0,Norman Jewison,Topol,39491,80500000.0,67.0
430,Doctor Zhivago,1965,197,Drama,8.0,David Lean,Omar Sharif,69903,111722000.0,69.0
484,The Irishman,2019,209,Biography,7.9,Martin Scorsese,Robert De Niro,324720,7000000.0,94.0
549,Spartacus,1960,197,Adventure,7.9,Stanley Kubrick,Kirk Douglas,124339,30000000.0,87.0
552,The Ten Commandments,1956,220,Adventure,7.9,Cecil B. DeMille,Charlton Heston,63560,93740000.0,NaN
579,M.S. Dhoni: The Untold Story,2016,184,Biography,7.8,Neeraj Pandey,Sushant Singh Rajput,40416,1782795.0,NaN
629,Veer-Zaara,2004,192,Drama,7.8,Yash Chopra,Shah Rukh Khan,49050,2921738.0,67.0
652,Titanic,1997,194,Drama,7.8,James Cameron,Leonardo DiCaprio,1046089,659325379.0,75.0
686,The Right Stuff,1983,193,Adventure,7.8,Philip Kaufman,Sam Shepard,56235,21500000.0,91.0
812,Hamlet,1996,242,Drama,7.7,Kenneth Branagh,Kenneth Branagh,35991,4414535.0,NaN
817,Short Cuts,1993,188,Comedy,7.7,Robert Altman,Andie MacDowell,42275,6110979.0,79.0
820,Malcolm X,1992,202,Biography,7.7,Spike Lee,Denzel Washington,85819,48169908.0,73.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0

In [18]:
print(csv_movies.groupby("Genre")["IMDB_Rating"].mean())

Genre
Action       7.949419
Adventure    7.937500
Animation    7.930488
Biography    7.938636
Comedy       7.901290
Crime        8.016822
Drama        7.957439
Family       7.800000
Fantasy      8.000000
Film-Noir    7.966667
Horror       7.909091
Mystery      7.975000
Thriller     7.800000
Western      8.350000
Name: IMDB_Rating, dtype: float64

In [19]:
csv_movies.groupby("Genre")["No_of_Votes"].sum()

Genre
Action       72282412
Adventure    22576163
Animation    21978630
Biography    24006844
Comedy       27620327
Crime        33533615
Drama        61367304
Family         551221
Fantasy        146222
Film-Noir      367215
Horror        3742556
Mystery       4203004
Thriller        27733
Western       1289665
Name: No_of_Votes, dtype: int64

In [20]:
csv_movies.groupby("Genre")["IMDB_Rating"].max()

Genre
Action       9.0
Adventure    8.6
Animation    8.6
Biography    8.9
Comedy       8.6
Crime        9.2
Drama        9.3
Family       7.8
Fantasy      8.1
Film-Noir    8.1
Horror       8.5
Mystery      8.4
Thriller     7.8
Western      8.8
Name: IMDB_Rating, dtype: float64

In [21]:
csv_movies.groupby("Genre").agg(
Average_Rating=("IMDB_Rating", "mean"),
Maximum_Rating=("IMDB_Rating", "max"),
Minimum_Rating=("IMDB_Rating", "min"),
Average_Runtime=("Runtime", "mean")
)

           Average_Rating  Maximum_Rating  Minimum_Rating  Average_Runtime
Genre
Action           7.949419             9.0             7.6       129.046512
Adventure        7.937500             8.6             7.6       134.111111
Animation        7.930488             8.6             7.6        99.585366
Biography        7.938636             8.9             7.6       136.022727
Comedy           7.901290             8.6             7.6       112.129032
Crime            8.016822             9.2             7.6       126.392523
Drama            7.957439             9.3             7.6       124.737024
Family           7.800000             7.8             7.8       107.500000
Fantasy          8.000000             8.1             7.9        85.000000
Film-Noir        7.966667             8.1             7.8       104.000000
Horror           7.909091             8.5             7.6       102.090909
Mystery          7.975000             8.4             7.6       119.083333
Thriller         7.800000             7.8             7.8       108.000000
Western          8.350000             8.8             7.8       148.250000

In [22]:
csv_movies.sort_values("IMDB_Rating",ascending = False).head(10)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
6,Pulp Fiction,1994,154,Crime,8.9,Quentin Tarantino,John Travolta,1826188,107928762.0,94.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0
9,Fight Club,1999,139,Drama,8.8,David Fincher,Brad Pitt,1854740,37030102.0,66.0

In [24]:
csv_movies.groupby("Genre")["IMDB_Rating"].mean().sort_values(ascending=False)

Genre
Western      8.350000
Crime        8.016822
Fantasy      8.000000
Mystery      7.975000
Film-Noir    7.966667
Drama        7.957439
Action       7.949419
Biography    7.938636
Adventure    7.937500
Animation    7.930488
Horror       7.909091
Comedy       7.901290
Family       7.800000
Thriller     7.800000
Name: IMDB_Rating, dtype: float64

In [25]:
csv_movies["Genre"].value_counts()

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: count, dtype: int64

In [26]:
csv_movies["Director"].value_counts()

Director
Alfred Hitchcock       14
Steven Spielberg       13
Hayao Miyazaki         11
Martin Scorsese        10
Akira Kurosawa         10
                       ..
Martin Rosen            1
Wolfgang Reitherman     1
Richard Lester          1
Blake Edwards           1
George Stevens          1
Name: count, Length: 548, dtype: int64

In [27]:
csv_movies["Director"].max()

'Ömer Faruk Sorak'

In [28]:
csv_movies.isnull().sum()

Series_Title       0
Released_Year      0
Runtime            0
Genre              0
IMDB_Rating        0
Director           0
Star1              0
No_of_Votes        0
Gross              0
Metascore        157
dtype: int64

In [29]:
csv_movies.dropna()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [31]:
csv_movies["Metascore"] = csv_movies["Metascore"].fillna(
csv_movies["Metascore"].mean()
)

In [32]:
csv_movies["Metascore"]

0       80.0
1      100.0
2       84.0
3       90.0
4       96.0
       ...
995     76.0
996     84.0
997     85.0
998     78.0
999     93.0
Name: Metascore, Length: 1000, dtype: float64

In [33]:
csv_movies[csv_movies["Released_Year"]>"2010"]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
18,Hamilton,2020,160,Biography,8.6,Thomas Kail,Lin-Manuel Miranda,55291,440984783.0,90.00000
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.00000
20,Soorarai Pottru,2020,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648.0,77.97153
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.00000
33,Joker,2019,122,Crime,8.5,Todd Phillips,Joaquin Phoenix,939252,335451311.0,59.00000
...,...,...,...,...,...,...,...,...,...,...
903,A Star Is Born,2018,136,Drama,7.6,Bradley Cooper,Lady Gaga,334312,215288866.0,88.00000
907,50/50,2011,100,Comedy,7.6,Jonathan Levine,Joseph Gordon-Levitt,315426,35014192.0,72.00000
910,Moneyball,2011,133,Biography,7.6,Bennett Miller,Brad Pitt,369529,75605492.0,87.00000
911,La piel que habito,2011,120,Drama,7.6,Pedro Almodóvar,Antonio Banderas,138959,3185812.0,70.00000
966,Apollo 13,PG,140,Adventure,7.6,Ron Howard,Tom Hanks,269197,173837933.0,77.00000

In [34]:
csv_movies[(csv_movies["IMDB_Rating"] > 8.5 ) & (csv_movies["No_of_Votes"] > 50000)]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.00000
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.00000
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.00000
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.00000
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.00000
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.00000
6,Pulp Fiction,1994,154,Crime,8.9,Quentin Tarantino,John Travolta,1826188,107928762.0,94.00000
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.00000
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.00000
9,Fight Club,1999,139,Drama,8.8,David Fincher,Brad Pitt,1854740,37030102.0,66.00000
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.00000
11,Forrest Gump,1994,142,Drama,8.8,Robert Zemeckis,Tom Hanks,1809221,330252182.0,82.00000
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.00000
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.00000
14,The Matrix,1999,136,Action,8.7,Lana Wachowski,Lilly Wachowski,1676426,171479930.0,73.00000
15,Goodfellas,1990,146,Biography,8.7,Martin Scorsese,Robert De Niro,1020727,46836394.0,90.00000
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.00000
17,One Flew Over the Cuckoo's Nest,1975,133,Drama,8.7,Milos Forman,Jack Nicholson,918088,112000000.0,83.00000
18,Hamilton,2020,160,Biography,8.6,Thomas Kail,Lin-Manuel Miranda,55291,440984783.0,90.00000
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.00000
20,Soorarai Pottru,2020,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648.0,77.97153
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.00000
22,Cidade de Deus,2002,130,Crime,8.6,Fernando Meirelles,Kátia Lund,699256,7563397.0,79.00000
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.00000
24,Saving Private Ryan,1998,169,Drama,8.6,Steven Spielberg,Tom Hanks,1235804,216540909.0,91.00000
25,The Green Mile,1999,189,Crime,8.6,Frank Darabont,Tom Hanks,1147794,136801374.0,61.00000
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.00000
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.00000
28,The Silence of the Lambs,1991,118,Crime,8.6,Jonathan Demme,Jodie Foster,1270197,130742922.0,85.00000
29,Star Wars,1977,121,Action,8.6,George Lucas,Mark Hamill,1231473,322740140.0,90.00000
31,Shichinin no samurai,1954,207,Action,8.6,Akira Kurosawa,Toshirô Mifune,315744,269061.0,98.00000
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.00000