In [1]:
import pandas as pd

data = {
"Patient_ID": [
"P101", "P102", "P103", "P104", "P105",
"P103", "P106", "P107", "P104", "P108"
],

"Patient_Name": [
"Amit", "Neha", "Rahul", "Pooja", "Sneha",
"Rahul", "Ravi", "Priya", "Pooja", "Karan"
],

"Age": [
45, 32, 56, 41, 29,
56, 63, 38, 41, 50
],

"City": [
"Nagpur", "Pune", "Mumbai", "Nagpur", "Pune",
"Mumbai", "Nagpur", "Pune", "Nagpur", "Mumbai"
],

"Department": [
"Cardiology", "Neurology", "Orthopedic", "Cardiology", "Neurology",
"Orthopedic", "Cardiology", "Neurology", "Cardiology", "Orthopedic"
],

"Treatment_Cost": [
50000, 35000, 60000, 45000, 30000,
60000, 70000, 40000, 45000, 55000
]
}

df = pd.DataFrame(data)

print(df)

  Patient_ID Patient_Name  Age    City  Department  Treatment_Cost
0       P101         Amit   45  Nagpur  Cardiology           50000
1       P102         Neha   32    Pune   Neurology           35000
2       P103        Rahul   56  Mumbai  Orthopedic           60000
3       P104        Pooja   41  Nagpur  Cardiology           45000
4       P105        Sneha   29    Pune   Neurology           30000
5       P103        Rahul   56  Mumbai  Orthopedic           60000
6       P106         Ravi   63  Nagpur  Cardiology           70000
7       P107        Priya   38    Pune   Neurology           40000
8       P104        Pooja   41  Nagpur  Cardiology           45000
9       P108        Karan   50  Mumbai  Orthopedic           55000

In [2]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
8     True
9    False
dtype: bool

In [3]:
df.duplicated().sum()

np.int64(2)

In [4]:
df[df.duplicated()]

  Patient_ID Patient_Name  Age    City  Department  Treatment_Cost
5       P103        Rahul   56  Mumbai  Orthopedic           60000
8       P104        Pooja   41  Nagpur  Cardiology           45000

In [5]:
df.drop_duplicates()

  Patient_ID Patient_Name  Age    City  Department  Treatment_Cost
0       P101         Amit   45  Nagpur  Cardiology           50000
1       P102         Neha   32    Pune   Neurology           35000
2       P103        Rahul   56  Mumbai  Orthopedic           60000
3       P104        Pooja   41  Nagpur  Cardiology           45000
4       P105        Sneha   29    Pune   Neurology           30000
6       P106         Ravi   63  Nagpur  Cardiology           70000
7       P107        Priya   38    Pune   Neurology           40000
9       P108        Karan   50  Mumbai  Orthopedic           55000

In [6]:
df["Patient_ID"].duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
8     True
9    False
Name: Patient_ID, dtype: bool

In [7]:
df[df["Patient_ID"].duplicated()]

  Patient_ID Patient_Name  Age    City  Department  Treatment_Cost
5       P103        Rahul   56  Mumbai  Orthopedic           60000
8       P104        Pooja   41  Nagpur  Cardiology           45000

In [9]:
df.drop_duplicates(subset=["Patient_ID"])

  Patient_ID Patient_Name  Age    City  Department  Treatment_Cost
0       P101         Amit   45  Nagpur  Cardiology           50000
1       P102         Neha   32    Pune   Neurology           35000
2       P103        Rahul   56  Mumbai  Orthopedic           60000
3       P104        Pooja   41  Nagpur  Cardiology           45000
4       P105        Sneha   29    Pune   Neurology           30000
6       P106         Ravi   63  Nagpur  Cardiology           70000
7       P107        Priya   38    Pune   Neurology           40000
9       P108        Karan   50  Mumbai  Orthopedic           55000

In [11]:
df.duplicated().sum()

np.int64(2)

In [12]:
df.drop_duplicates(subset="Patient_ID")

  Patient_ID Patient_Name  Age    City  Department  Treatment_Cost
0       P101         Amit   45  Nagpur  Cardiology           50000
1       P102         Neha   32    Pune   Neurology           35000
2       P103        Rahul   56  Mumbai  Orthopedic           60000
3       P104        Pooja   41  Nagpur  Cardiology           45000
4       P105        Sneha   29    Pune   Neurology           30000
6       P106         Ravi   63  Nagpur  Cardiology           70000
7       P107        Priya   38    Pune   Neurology           40000
9       P108        Karan   50  Mumbai  Orthopedic           55000

In [14]:
df.drop_duplicates(subset=["Patient_ID"],keep = "first")

  Patient_ID Patient_Name  Age    City  Department  Treatment_Cost
0       P101         Amit   45  Nagpur  Cardiology           50000
1       P102         Neha   32    Pune   Neurology           35000
2       P103        Rahul   56  Mumbai  Orthopedic           60000
3       P104        Pooja   41  Nagpur  Cardiology           45000
4       P105        Sneha   29    Pune   Neurology           30000
6       P106         Ravi   63  Nagpur  Cardiology           70000
7       P107        Priya   38    Pune   Neurology           40000
9       P108        Karan   50  Mumbai  Orthopedic           55000

In [15]:
df["Treatment_Cost"].quantile(0.50)

np.float64(47500.0)

In [16]:
df["Treatment_Cost"].quantile(0.75)

np.float64(58750.0)